export const allWeatherIcons = {
  '01d': '/iconsWeather/ClearSky.svg',
  '01n': '/iconsWeather/ClearSky.svg',
  '02d': '/iconsWeather/FewClouds.svg',
  '02d': '/iconsWeather/FewClouds.svg',
  '03d': '/iconsWeather/ScatteredClouds.svg',
  '03n': '/iconsWeather/ScatteredClouds.svg',
  '04d': '/iconsWeather/BrokenClouds.svg',
  '04n': '/iconsWeather/BrokenClouds.svg',
  '09d': '/iconsWeather/Rain.svg',
  '09n': '/iconsWeather/Rain.svg',
  '10d': '/iconsWeather/Rain.svg',
  '10n': '/iconsWeather/Rain.svg',
  '11d': '/iconsWeather/RainThunder.svg',
  '11n': '/iconsWeather/RainThunder.svg',
  '13d': '/iconsWeather/Snow.svg',
  '13n': '/iconsWeather/Snow.svg',
  '50d': '/iconsWeather/Mist.svg',
  '50n': '/iconsWeather/Mist.svg',
}
